export const teams = [
  { id: 1, name: "McLaren", base: "Woking, United Kingdom" },
  { id: 2, name: "Mercedes", base: "Brackley, United Kingdom" },
  { id: 3, name: "Red Bull Racing", base: "Milton Keynes, United Kingdom" },
  { id: 4, name: "Ferrari", base: "Maranello, Italy" },
  { id: 5, name: "Alpine", base: "Enstone, United Kingdom" },
  { id: 6, name: "Aston Martin", base: "Silverstone, United Kingdom" },
  { id: 7, name: "Alfa Romeo Racing", base: "Hinwil, Switzerland" },
  { id: 8, name: "AlphaTauri", base: "Faenza, Italy" },
  { id: 9, name: "Williams", base: "Grove, United Kingdom" },
  { id: 10, name: "Haas", base: "Kannapolis, United States" },
  { id: 11, name: "Uralkali Haas F1 Team", base: "Banbury, United Kingdom" },
  { id: 12, name: "Scuderia Toro Rosso", base: "Faenza, Italy" },
];

export const drivers = [
  { id: 1, name: "Max Verstappen", team: "Red Bull Racing" },
  { id: 2, name: "Liam Lawson", team: "Red Bull Racing" },
  { id: 3, name: "Yuki Tsunoda", team: "Racing Bulls" },
  { id: 4, name: "Isack Hadjar", team: "Racing Bulls" },
  { id: 5, name: "Charles Leclerc", team: "Ferrari" },
  { id: 6, name: "Lewis Hamilton", team: "Ferrari" },
  { id: 7, name: "George Russell", team: "Mercedes" },
  { id: 8, name: "Andrea Kimi Antonelli", team: "Mercedes" },
  { id: 9, name: "Lando Norris", team: "McLaren" },
  { id: 10, name: "Oscar Piastri", team: "McLaren" },
  { id: 11, name: "Fernando Alonso", team: "Aston Martin" },
  { id: 12, name: "Lance Stroll", team: "Aston Martin" },
  { id: 13, name: "Pierre Gasly", team: "Alpine" },
  { id: 14, name: "Jack Doohan", team: "Alpine" },
  { id: 15, name: "Franco Colapinto", team: "Alpine" },
  { id: 16, name: "Esteban Ocon", team: "Haas" },
  { id: 17, name: "Oliver Bearman", team: "Haas" },
  { id: 18, name: "Alex Albon", team: "Williams" },
  { id: 19, name: "Carlos Sainz Jr.", team: "Williams" },
  { id: 20, name: "Nico Hülkenberg", team: "Stake F1 Team" },
  { id: 21, name: "Gabriel Bortoleto", team: "Stake F1 Team" },
];

